name: "Nuclei Scanning - Action"
description: ""

inputs:
  urls-txt:
    description: "List of urls to run templates"
    required: true
  slack-token:
    description: "Slack token"
    required: true
  slack-channel:
    description: "Slack channel"
    required: true

outputs:
  random-number:
    description: "Random number"
    value: "42"

runs:
  using: "composite"
  steps:
    - run: |
        ls -la /home/runner/work/_temp_/
        ls -la /home/runner/work/_temp_/_github_home/
      shell: bash
