name: "Nuclei Scanning - Action"
description: ""

inputs:
  urls-txt:
    description: "List of urls to run templates"
    required: true
  slack-token:
    description: "Slack token"
    required: true
  slack-channel:
    description: "Slack channel"
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        ls -la /home/runner/work/
        echo $GITHUB_WORKSPACE
      shell: bash
