name: "Nuclei Scanning - Action"
description: ""

inputs:
  urls-txt:
    description: "List of urls to run templates"
    required: true
    default: "URLs.txt"
  slack-token:
    description: "Slack token"
    required: true
  slack-channel:
    description: "Slack channel"
    required: true

outputs:
  random-number:
    description: "Random number"
    value: "42"

runs:
  using: "composite"
  steps:
    - run: GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
      shell: bash
    - run: |
        echo test
        pwd
        echo ${{ github.action_path }}
        ls -la
      shell: bash
    - run: |
        $HOME/go/bin/nuclei -l ${{ inputs.urls-txt }} \
          -json \
          -update-directory . \
          -update-templates \
          -t nuclei-templates/cves/ \
          -t nuclei-templates/files/ \
          -t nuclei-templates/security-misconfiguration/ \
          -t nuclei-templates/subdomain-takeover/ \
          -t nuclei-templates/vulnerabilities/ \
          -o output.txt
      shell: bash
    - run: |
        git clone https://github.com/aqme/appsec-etl.git
        pip3 install -U setuptools
        pip3 install slackclient
        cat output.txt
        cat output.txt | python3 ${{ github.action_path }}/appsec-etl/transform/nuclei.py | python3 ${{ github.action_path }}/appsec-etl/load/toslack.py
      shell: bash
